## Numpy

#### №1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
print(format(a.shape))

(5, 2)


#### №2

In [4]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

#### №3

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp

8.0

In [7]:
print(a_centered_sp / 4)

2.0


#### №4

In [8]:
m = a.T

In [9]:
cov_a = np.cov(m)
cov_a

array([[1. , 2. ],
       [2. , 4.3]])

In [10]:
print(cov_a[0, 1])

2.0


## Pandas

#### №1

In [11]:
import pandas as pd

In [12]:
authors = pd.DataFrame({'author_id' : [1, 2, 3], 'author_name' : ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [13]:
book = pd.DataFrame({'author_id' : [1, 1, 1, 2, 2, 3, 3], 
                     'book_title ' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо',
                                      'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price' : [450, 300, 350, 500, 450, 370, 290]})
book

author_id           book_title   price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### №2

In [14]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name           book_title   price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### №3

In [15]:
top5 = pd.DataFrame(authors_price.nlargest(5, 'price'))
top5

author_id author_name        book_title   price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

#### №4

In [16]:
X1 = (authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'}))
X2 = (authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'}))
X3 = (authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'}))
authors_stat = pd.DataFrame(pd.concat([X1, X2, X3], axis = 1))
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

#### №5

In [17]:
authors_price.loc[authors_price['author_id'].notnull(), 'cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_pric

NameError: name 'authors_pric' is not defined

In [ ]:
book_info = pd.pivot_table(authors_price, values= ['price'], index= ['author_name'], columns= ['cover'], aggfunc= np.sum)
book_info